const fl = (n) => Array.from({ length: n }, (_, i) => `fk${i}`);

export const DUMMY_POSTS = [
  {
    _id: "d1",
    text: "Just finished redesigning my portfolio site from scratch. Dark mode, micro-animations, the whole thing. Six months ago I didn't know what CSS was. Wild how fast things can change.",
    img: null,
    user: {
      _id: "u1",
      username: "arianmk",
      fullName: "Arian Mehmetaj",
      profileImg: null,
    },
    comments: [
      { _id: "c1", text: "Looks absolutely clean. Share the link!", user: { username: "lena_dev", fullName: "Lena Voss" } },
    ],
    likes: ["u2", "u3", "u5"],
    createdAt: new Date(Date.now() - 1000 * 60 * 18).toISOString(),
  },
  {
    _id: "d2",
    text: "Morning light through old geometric tiles in the medina. Some patterns haven't changed in 700 years — and they're still more elegant than anything I can design.",
    img: null,
    user: {
      _id: "u2",
      username: "zara.visuals",
      fullName: "Zara Ibrahimi",
      profileImg: null,
    },
    comments: [],
    likes: ["u1", "u4", "u6", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    _id: "d3",
    text: "Hot take: most UI design problems are actually UX writing problems. Fix the copy first. The layout almost always fixes itself.",
    img: null,
    user: {
      _id: "u3",
      username: "tomislav.ux",
      fullName: "Tomislav Perić",
      profileImg: null,
    },
    comments: [
      { _id: "c3", text: "This is exactly what I needed to hear today.", user: { username: "arianmk", fullName: "Arian Mehmetaj" } },
      { _id: "c4", text: "Hard agree. We spent 3 sprints on layout, changed one headline, problem solved.", user: { username: "zara.visuals", fullName: "Zara Ibrahimi" } },
    ],
    likes: ["u1", "u2", "u4", "u5", "u6"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    _id: "d4",
    text: "Built a tiny CLI tool this weekend that auto-generates color tokens from any image. Drop in a photo, get a full Tailwind palette out. Open source, link in bio.",
    img: null,
    user: {
      _id: "u4",
      username: "nilufar.codes",
      fullName: "Nilufar Rashidova",
      profileImg: null,
    },
    comments: [
      { _id: "c5", text: "This is genuinely useful. Starred.", user: { username: "tomislav.ux", fullName: "Tomislav Perić" } },
    ],
    likes: ["u1", "u3", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    _id: "d5",
    text: "The difference between a good developer and a great one isn't the code they write — it's knowing when not to write any code at all.",
    img: null,
    user: {
      _id: "u5",
      username: "d.karimov",
      fullName: "Damir Karimov",
      profileImg: null,
    },
    comments: [],
    likes: ["u2", "u3", "u4", "u6"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    _id: "d7",
    text: "Spent the morning in the forest with no phone signal. Came back with more ideas than a week of doom-scrolling gave me. Highly recommend scheduled disconnection.",
    img: null,
    user: {
      _id: "u7",
      username: "lena_dev",
      fullName: "Lena Voss",
      profileImg: null,
    },
    comments: [
      { _id: "c8", text: "Doing this every Sunday now. Changes everything.", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: ["u2", "u4", "u6"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
  },
  {
    _id: "d8",
    text: "Design is not just what it looks like and feels like. Design is how it works. Applies to code architecture just as much as UI.",
    img: null,
    user: {
      _id: "u3",
      username: "tomislav.ux",
      fullName: "Tomislav Perić",
      profileImg: null,
    },
    comments: [],
    likes: ["u1", "u5", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 28).toISOString(),
  },
  {
    _id: "d9",
    text: "Newsletter writing tip: your subject line is the only thing that matters until someone opens the email. Spend more time on 8 words than on 800.",
    img: null,
    user: {
      _id: "u8",
      username: "marco.writes",
      fullName: "Marco Bellini",
      profileImg: null,
    },
    comments: [
      { _id: "c9a", text: "This changed how I approach every campaign.", user: { username: "lena_dev", fullName: "Lena Voss" } },
    ],
    likes: ["u1", "u3", "u5", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    _id: "d10",
    text: "Every feature you add without removing something is a UX debt. The hardest part of product management isn't saying yes — it's saying no convincingly.",
    img: null,
    user: {
      _id: "u9",
      username: "priya.builds",
      fullName: "Priya Nair",
      profileImg: null,
    },
    comments: [
      { _id: "c10a", text: "This is the entire job in two sentences.", user: { username: "tomislav.ux", fullName: "Tomislav Perić" } },
      { _id: "c10b", text: "Bookmarking this for my next sprint retro.", user: { username: "arianmk", fullName: "Arian Mehmetaj" } },
    ],
    likes: ["u2", "u3", "u4", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    _id: "d11",
    text: "The golden hour isn't a time — it's a discipline. Being there with intention, not just luck, is 90% of what separates a good photo from a forgettable one.",
    img: null,
    user: {
      _id: "u10",
      username: "felix.foto",
      fullName: "Felix Hartmann",
      profileImg: null,
    },
    comments: [],
    likes: ["u2", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
  },
  {
    _id: "d12",
    text: "Cleaned up a dataset this morning that took 4 hours manually every week. Wrote a 30-line Python script. Now it runs in 8 seconds. This is why I love what I do.",
    img: null,
    user: {
      _id: "u11",
      username: "sofia.data",
      fullName: "Sofia Andersen",
      profileImg: null,
    },
    comments: [
      { _id: "c12a", text: "What are you using for the cleaning? Pandas?", user: { username: "nilufar.codes", fullName: "Nilufar Rashidova" } },
    ],
    likes: ["u1", "u4", "u5"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 13).toISOString(),
  },
  {
    _id: "d13",
    text: "We don't fear the unknown. We fear losing what we know. Most 'risk aversion' is really just comfort maintenance with better PR.",
    img: null,
    user: {
      _id: "u12",
      username: "kai.thinks",
      fullName: "Kai Yamamoto",
      profileImg: null,
    },
    comments: [
      { _id: "c13a", text: "Sitting with this one for a while.", user: { username: "zara.visuals", fullName: "Zara Ibrahimi" } },
    ],
    likes: ["u1", "u2", "u3", "u5", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 17).toISOString(),
  },
  {
    _id: "d14",
    text: "Ran 5km before 6am three days in a row. The goal was never the distance — it was proving to myself that I show up when I say I will.",
    img: null,
    user: {
      _id: "u13",
      username: "nadia.runs",
      fullName: "Nadia Osei",
      profileImg: null,
    },
    comments: [],
    likes: ["u2", "u5"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
  {
    _id: "d15",
    text: "Unpopular opinion: your API response structure is part of your product. If a client dev has to read 200 lines of docs to understand what your endpoint returns, you shipped a bug.",
    img: null,
    user: {
      _id: "u14",
      username: "carlos.dev",
      fullName: "Carlos Ruiz",
      profileImg: null,
    },
    comments: [
      { _id: "c15a", text: "Finally someone said it.", user: { username: "nilufar.codes", fullName: "Nilufar Rashidova" } },
      { _id: "c15b", text: "Printing this and putting it in the office.", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: ["u1", "u3", "u4", "u5", "u7"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30).toISOString(),
  },
  {
    _id: "d16",
    text: "Redesigned our onboarding flow using only empty states as the guide. If you design the empty state first, the rest of the product logic becomes obvious.",
    img: null,
    user: {
      _id: "u15",
      username: "ayla.design",
      fullName: "Ayla Yilmaz",
      profileImg: null,
    },
    comments: [
      { _id: "c16a", text: "This is actually a great mental model.", user: { username: "tomislav.ux", fullName: "Tomislav Perić" } },
    ],
    likes: ["u1", "u3"],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
  },
];

export const DUMMY_SUGGESTED_USERS = [
  { _id: "u8", username: "marco.writes", fullName: "Marco Bellini", profileImg: null, followers: [], following: [] },
  { _id: "u11", username: "sofia.data", fullName: "Sofia Andersen", profileImg: null, followers: [], following: [] },
  { _id: "u15", username: "ayla.design", fullName: "Ayla Yilmaz", profileImg: null, followers: [], following: [] },
];

export const DUMMY_EXPLORE_POSTS = [
  {
    _id: "dex1",
    text: "GPT-4 helped me debug a race condition I'd been staring at for three days. AI pair programming isn't the future — it's already the present.",
    img: null,
    user: { _id: "u14", username: "carlos.dev", fullName: "Carlos Ruiz", profileImg: null },
    comments: [
      { _id: "exc1a", text: "Race conditions are the worst. Congrats on killing it.", user: { username: "nilufar.codes", fullName: "Nilufar Rashidova" } },
      { _id: "exc1b", text: "The AI didn't debug it. Sleep deprivation just lowered your standards 😂", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: fl(214),
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    category: "tech",
  },
  {
    _id: "dex2",
    text: "The best books don't give you answers. They make the questions feel necessary. Currently reading 'The Dawn of Everything' and I can't stop highlighting.",
    img: null,
    user: { _id: "u8", username: "marco.writes", fullName: "Marco Bellini", profileImg: null },
    comments: [
      { _id: "exc2a", text: "One of the best books of the decade, full stop.", user: { username: "kai.thinks", fullName: "Kai Yamamoto" } },
      { _id: "exc2b", text: "Just added it to my list.", user: { username: "zara.visuals", fullName: "Zara Ibrahimi" } },
    ],
    likes: fl(389),
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    category: "culture",
  },
  {
    _id: "dex3",
    text: "A non-developer asked me what I do for work. I said 'I move text files around and things happen on screens.' They seemed satisfied. I'm choosing to believe I nailed it.",
    img: null,
    user: { _id: "u11", username: "sofia.data", fullName: "Sofia Andersen", profileImg: null },
    comments: [
      { _id: "exc3a", text: "I'm stealing this as my LinkedIn headline immediately.", user: { username: "arianmk", fullName: "Arian Mehmetaj" } },
      { _id: "exc3b", text: "My therapist asked me the same question. Same answer.", user: { username: "carlos.dev", fullName: "Carlos Ruiz" } },
    ],
    likes: fl(531),
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    category: "humor",
  },
  {
    _id: "dex4",
    text: "Your immune system eliminates roughly 10 billion potentially cancerous cells per day — and you never once feel it happen. Biology is incomprehensibly good at its job.",
    img: null,
    user: { _id: "u12", username: "kai.thinks", fullName: "Kai Yamamoto", profileImg: null },
    comments: [
      { _id: "exc4a", text: "And yet one misfolded protein can unravel everything. Both things are simultaneously true.", user: { username: "sofia.data", fullName: "Sofia Andersen" } },
    ],
    likes: fl(762),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    category: "science",
  },
  {
    _id: "dex5",
    text: "Just merged my first PR to a major open source project. It was two lines of code. I'm celebrating anyway.",
    img: null,
    user: { _id: "u1", username: "arianmk", fullName: "Arian Mehmetaj", profileImg: null },
    comments: [
      { _id: "exc5a", text: "Two lines shipped beats 200 lines in draft. Congrats.", user: { username: "lena_dev", fullName: "Lena Voss" } },
      { _id: "exc5b", text: "That first merged PR feeling never gets old. 🎉", user: { username: "nilufar.codes", fullName: "Nilufar Rashidova" } },
    ],
    likes: fl(843),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    category: "tech",
  },
  {
    _id: "dex6",
    text: "Stop shooting in auto mode. Not because manual is better — but because understanding why the camera makes each choice teaches you to see light differently.",
    img: null,
    user: { _id: "u10", username: "felix.foto", fullName: "Felix Hartmann", profileImg: null },
    comments: [
      { _id: "exc6a", text: "This is the advice I wish someone gave me in year one.", user: { username: "zara.visuals", fullName: "Zara Ibrahimi" } },
    ],
    likes: fl(294),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    category: "culture",
  },
  {
    _id: "dex7",
    text: "Made miso soup from scratch using a dashi broth I steeped overnight. The difference between instant and real is not a matter of taste — it's a matter of patience.",
    img: null,
    user: { _id: "u12", username: "kai.thinks", fullName: "Kai Yamamoto", profileImg: null },
    comments: [
      { _id: "exc7a", text: "Would you share the dashi recipe? I've been intimidated by it.", user: { username: "nadia.runs", fullName: "Nadia Osei" } },
    ],
    likes: fl(156),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    category: "lifestyle",
  },
  {
    _id: "dex8",
    text: "Two years ago I couldn't get interviews. Today we closed our seed round. The gap between those two moments was mostly rejection letters and refusing to stop.",
    img: null,
    user: { _id: "u9", username: "priya.builds", fullName: "Priya Nair", profileImg: null },
    comments: [
      { _id: "exc8a", text: "Congrats!! This is huge. 🎉", user: { username: "arianmk", fullName: "Arian Mehmetaj" } },
      { _id: "exc8b", text: "The compounding effect of not quitting. Respect.", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: fl(1247),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    category: "culture",
  },
  {
    _id: "dex9",
    text: "Accessibility is not a feature. It's not a sprint ticket. It's not 'we'll handle it later.' It is the baseline. Everything else is decoration.",
    img: null,
    user: { _id: "u15", username: "ayla.design", fullName: "Ayla Yilmaz", profileImg: null },
    comments: [
      { _id: "exc9a", text: "The number of 'accessible version' subdomains I've seen in the wild is embarrassing.", user: { username: "tomislav.ux", fullName: "Tomislav Perić" } },
    ],
    likes: fl(672),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    category: "tech",
  },
  {
    _id: "dex10",
    text: "Ran the Berlin Half Marathon this morning. 1:44:12. A year ago I couldn't run 3km without stopping. Evidence that most limits are self-imposed.",
    img: null,
    user: { _id: "u13", username: "nadia.runs", fullName: "Nadia Osei", profileImg: null },
    comments: [
      { _id: "exc10a", text: "That's an incredible time. Well done!", user: { username: "lena_dev", fullName: "Lena Voss" } },
      { _id: "exc10b", text: "The progress in one year is remarkable. 🔥", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: fl(923),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    category: "sports",
  },
  {
    _id: "dex11",
    text: "There's a difference between being alone and being lonely. One is a state. The other is a wound. Learning to be comfortable in solitude is one of the most underrated skills.",
    img: null,
    user: { _id: "u12", username: "kai.thinks", fullName: "Kai Yamamoto", profileImg: null },
    comments: [
      { _id: "exc11a", text: "And most people never learn to distinguish them.", user: { username: "marco.writes", fullName: "Marco Bellini" } },
    ],
    likes: fl(1089),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    category: "culture",
  },
  {
    _id: "dex12",
    text: "Hot take: TypeScript tricks people into thinking type safety replaces good architecture. Two different concerns. You can have one without the other. Change my mind.",
    img: null,
    user: { _id: "u14", username: "carlos.dev", fullName: "Carlos Ruiz", profileImg: null },
    comments: [
      { _id: "exc12a", text: "Type safety and architecture serve different concerns. Both can be weak independently.", user: { username: "nilufar.codes", fullName: "Nilufar Rashidova" } },
      { _id: "exc12b", text: "I both agree and disagree so hard it's giving me a headache.", user: { username: "lena_dev", fullName: "Lena Voss" } },
      { _id: "exc12c", text: "Coming from a Rust background, this whole debate is adorable.", user: { username: "d.karimov", fullName: "Damir Karimov" } },
    ],
    likes: fl(487),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
    category: "tech",
  },
  {
    _id: "dex13",
    text: "Spent a week in Lisbon without plans. No reservations, no itinerary. Just walked until I was lost, ate where the menus were handwritten. Highly recommend.",
    img: null,
    user: { _id: "u2", username: "zara.visuals", fullName: "Zara Ibrahimi", profileImg: null },
    comments: [
      { _id: "exc13a", text: "Lisbon rewards exactly this approach.", user: { username: "marco.writes", fullName: "Marco Bellini" } },
    ],
    likes: fl(344),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 14).toISOString(),
    category: "lifestyle",
  },
  {
    _id: "dex14",
    text: "Career advice I wish I'd gotten earlier: the job listing is a wish list. Apply anyway. The gap between what they ask for and what they'll accept is enormous.",
    img: null,
    user: { _id: "u8", username: "marco.writes", fullName: "Marco Bellini", profileImg: null },
    comments: [
      { _id: "exc14a", text: "Applied to a role asking for 7 years of experience. Got the job. Had 2.", user: { username: "arianmk", fullName: "Arian Mehmetaj" } },
      { _id: "exc14b", text: "They write for the perfect candidate. They hire for fit.", user: { username: "priya.builds", fullName: "Priya Nair" } },
    ],
    likes: fl(2104),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 16).toISOString(),
    category: "culture",
  },
  {
    _id: "dex15",
    text: "Installed solar panels last year. This month we generated more power than we consumed for the first time. It's a small thing. It still matters.",
    img: null,
    user: { _id: "u13", username: "nadia.runs", fullName: "Nadia Osei", profileImg: null },
    comments: [
      { _id: "exc15a", text: "Small actions compound over time. This is genuinely inspiring.", user: { username: "kai.thinks", fullName: "Kai Yamamoto" } },
    ],
    likes: fl(567),
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    category: "lifestyle",
  },
];

export const DUMMY_NOTIFICATIONS = [
  {
    _id: "dn1",
    type: "follow",
    from: { _id: "u3", username: "tomislav.ux", fullName: "Tomislav Perić", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
  },
  {
    _id: "dn2",
    type: "like",
    from: { _id: "u4", username: "nilufar.codes", fullName: "Nilufar Rashidova", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
  },
  {
    _id: "dn3",
    type: "follow",
    from: { _id: "u10", username: "felix.foto", fullName: "Felix Hartmann", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 50).toISOString(),
  },
  {
    _id: "dn4",
    type: "like",
    from: { _id: "u2", username: "zara.visuals", fullName: "Zara Ibrahimi", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 75).toISOString(),
  },
  {
    _id: "dn5",
    type: "like",
    from: { _id: "u15", username: "ayla.design", fullName: "Ayla Yilmaz", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 10).toISOString(),
  },
  {
    _id: "dn6",
    type: "follow",
    from: { _id: "u9", username: "priya.builds", fullName: "Priya Nair", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    _id: "dn7",
    type: "like",
    from: { _id: "u12", username: "kai.thinks", fullName: "Kai Yamamoto", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    _id: "dn8",
    type: "follow",
    from: { _id: "u13", username: "nadia.runs", fullName: "Nadia Osei", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    _id: "dn9",
    type: "like",
    from: { _id: "u8", username: "marco.writes", fullName: "Marco Bellini", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    _id: "dn10",
    type: "follow",
    from: { _id: "u11", username: "sofia.data", fullName: "Sofia Andersen", profileImg: null },
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
  },
];

export const DUMMY_CONVERSATIONS = [
  {
    _id: "conv1",
    partner: { _id: "u2", username: "zara.visuals", fullName: "Zara Ibrahimi", profileImg: null },
    unreadCount: 2,
    messages: [
      { _id: "dm1_1", text: "Hey! Loved that post about the medina tiles.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 30).toISOString() },
      { _id: "dm1_2", text: "Thank you! Those were from my trip to Marrakech last spring. The patterns in person are insane.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 28).toISOString() },
      { _id: "dm1_3", text: "I'm planning a trip there in autumn. Any recommendations?", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 10).toISOString() },
      { _id: "dm1_4", text: "Stay in the medina, not outside the walls. The entire vibe changes. Also Bahia Palace at 8am before the crowds.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2 - 1000 * 60 * 8).toISOString() },
      { _id: "dm1_5", text: "That's actually perfect advice. I'll book early entry.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1 - 1000 * 60 * 5).toISOString() },
      { _id: "dm1_6", text: "Also Café de Épices for lunch — the rooftop view is worth every minute of the wait.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 1 - 1000 * 60 * 3).toISOString() },
      { _id: "dm1_7", text: "You're literally saving this trip 😭 Thank you!", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 14).toISOString() },
      { _id: "dm1_8", text: "Send me photos when you go!", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 12).toISOString() },
    ],
  },
  {
    _id: "conv2",
    partner: { _id: "u4", username: "nilufar.codes", fullName: "Nilufar Rashidova", profileImg: null },
    unreadCount: 0,
    messages: [
      { _id: "dm2_1", text: "Hey, I saw your color token CLI on GitHub — is the extraction using k-means clustering?", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48 - 1000 * 60 * 40).toISOString() },
      { _id: "dm2_2", text: "Yeah, k-means with k=5 by default. You can override it in the config. Did you try it?", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48 - 1000 * 60 * 35).toISOString() },
      { _id: "dm2_3", text: "Just ran it on a sunset photo and got the most beautiful warm palette. Dropped it straight into Tailwind.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48 - 1000 * 60 * 20).toISOString() },
      { _id: "dm2_4", text: "That's exactly what I built it for haha. Sunset photos are always the best inputs.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48 - 1000 * 60 * 18).toISOString() },
      { _id: "dm2_5", text: "Would you be open to adding a --format css-vars flag? I'd use it constantly.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 - 1000 * 60 * 10).toISOString() },
      { _id: "dm2_6", text: "Great idea, I'll add it to the roadmap. PRs are also welcome if you want to take a crack at it!", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 - 1000 * 60 * 5).toISOString() },
      { _id: "dm2_7", text: "I might do that! Let me look at the source this weekend.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString() },
    ],
  },
  {
    _id: "conv3",
    partner: { _id: "u3", username: "tomislav.ux", fullName: "Tomislav Perić", profileImg: null },
    unreadCount: 1,
    messages: [
      { _id: "dm3_1", text: "Reviewed your design spec. The information architecture is solid but I'd reconsider the nav placement on mobile.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5 - 1000 * 60 * 20).toISOString() },
      { _id: "dm3_2", text: "Interesting. What's the concern — thumb reach?", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5 - 1000 * 60 * 15).toISOString() },
      { _id: "dm3_3", text: "Partly thumb reach, but also mental model. Users expect primary actions bottom-right, not top-left on mobile.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5 - 1000 * 60 * 10).toISOString() },
      { _id: "dm3_4", text: "Makes sense. I'll prototype both and run a quick usability test.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5 - 1000 * 60 * 7).toISOString() },
      { _id: "dm3_5", text: "Good call. Let me know the results — genuinely curious which wins.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
      { _id: "dm3_6", text: "Also, loved your tweet about UX writing today. Shared it with our whole product team.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 32).toISOString() },
    ],
  },
  {
    _id: "conv4",
    partner: { _id: "u5", username: "d.karimov", fullName: "Damir Karimov", profileImg: null },
    unreadCount: 0,
    messages: [
      { _id: "dm4_1", text: "Are you going to the Berlin tech meetup in July?", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString() },
      { _id: "dm4_2", text: "Hadn't planned to. What's the lineup?", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 71 - 1000 * 60 * 30).toISOString() },
      { _id: "dm4_3", text: "Distributed systems and Rust ecosystem talks mostly. Should be solid.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 71).toISOString() },
      { _id: "dm4_4", text: "Rust ecosystem has been moving fast. I'd go just for that track.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 70 - 1000 * 60 * 45).toISOString() },
      { _id: "dm4_5", text: "I'll send you the link when registration opens.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 70).toISOString() },
      { _id: "dm4_6", text: "Appreciate it.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 69 - 1000 * 60 * 50).toISOString() },
    ],
  },
  {
    _id: "conv5",
    partner: { _id: "u7", username: "lena_dev", fullName: "Lena Voss", profileImg: null },
    unreadCount: 3,
    messages: [
      { _id: "dm5_1", text: "How did the system design interview go yesterday?", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20 - 1000 * 60 * 30).toISOString() },
      { _id: "dm5_2", text: "Honestly rough. I blanked on the database sharding question for a second.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20 - 1000 * 60 * 25).toISOString() },
      { _id: "dm5_3", text: "Ugh, those are always the worst. Did you recover?", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20 - 1000 * 60 * 22).toISOString() },
      { _id: "dm5_4", text: "Yeah, walked through consistent hashing and they seemed okay with the recovery. We'll see.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20 - 1000 * 60 * 18).toISOString() },
      { _id: "dm5_5", text: "Recovering from a blank is itself a signal. Shows composure under pressure.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString() },
      { _id: "dm5_6", text: "That's a good way to look at it.", fromMe: true, createdAt: new Date(Date.now() - 1000 * 60 * 60 * 17 - 1000 * 60 * 45).toISOString() },
      { _id: "dm5_7", text: "Let me know the moment you hear back!", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString() },
      { _id: "dm5_8", text: "Also heads up — there's a React performance talk at the meetup Thursday if you're free.", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString() },
      { _id: "dm5_9", text: "Sharing the event link now ↓", fromMe: false, createdAt: new Date(Date.now() - 1000 * 60 * 28).toISOString() },
    ],
  },
];